[[oneTBB]]
arch = "aarch64"
git-tree-sha1 = "49cabcd0a0d0aa13ce854748dafe894385e6e78e"
os = "macos"

    [[oneTBB.download]]
    sha256 = "7538d9d4046d17c7ba472b1a2c194d7595294e133db89ffb4c4b51554ab51d4a"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.aarch64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "646d9eae15c40ed79900c59c1da043734f970149"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "cb618c3ba4b1b083b8c8ed18de429ec72f54588356f9d2b73773b5aec0413f40"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.aarch64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0dffbfbc0dfe47e8712d3077d17752da02592279"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "72465b0c0a8e000a269c9fb85cd7029d392a2f27b4f91bb529b3f3d27d01a8c2"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.aarch64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c78c3aeddcf23b89b81df1afd82e26327b31e884"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "39a7f3b90d99d4db1c33780ea7ee4525a907f03d3c366b84ef06c6e493e09d7c"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.aarch64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "513a0e96277aa8b4dddc529d7bfba6448d306d96"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "efccb7f2eef7fa4e50ab7355e2144e9c36a862a5ea870f2667c4a4288f3321cd"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.aarch64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a637ac3a02bb0015410fc79f76bf070ac4a5ba82"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "f7501de7f093f89b9758cf0afc80e5a54de5646a5f7e8c840500da508b3ed400"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13af658cc41b4cd2e616b11fedce954e4f41e38d"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "e778eeceb0efd1b29366ab89b75de5913de9eabddd918768da6cd1ca74063a6e"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2e8b6b9b30fddc60ee841e5c248ecf30541ac81"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "41664fb05e536be6f64a7d3cd1c8b3071127bd6d411699cd86a8d825f5f2cce5"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "baf64cb96c96ce07a32885017451e6622b4c7577"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "9fb9286a14743be4adec95c73eab94ebcdbe835756877a5b4b60972129efc4af"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2171542208424a636fd91a89bce66033c0bd11d0"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "3ce8095bce3b4e7a4f9ca8437418f9407f354f6f49bdb541754bd15dc6dc09c4"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cdecc83d2ef65602fa210e412921d313ea86de3"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "2d334258e1cbe55991cb14ee420f0994b88b57759d7731d3fad6c137aaf17336"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13540c3c96c1a1e71da0ed739282d5dc7b67b5bd"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "40b8e73ebf03981aed69cad2e32a8b8d55e5fcee396cdc6153a53765558a54c6"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29dc75c4acd351dc3b97b462a0e6528dac6cfe8c"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "798ae771cd2296c3943063a7fe4ff2da1dc0f25d5231d727bdf9854a9589cd09"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a35a2f59247de432fcd84eebfe086ab1d2adeed"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "8ab5f4b085b1cf463a84ba17348499a397bf0fac7f95b0380d500fcfaa19dace"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.i686-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39fa308320dd2224ea2fe3fd6f1bee210f7c4779"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "5ecb031e7e2b0621819b326c3255d0d9faa63a29b617cdf60645252f065d3287"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.i686-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a45de545c675d79ae62ac49782675f80738fa72b"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "1cb8ed45144232c4f259f49b51831141e49e66afdec5a0e9587a18e9955725eb"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.i686-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7456950f86c9e4989eb05051b76bec7f084a8fec"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "8b7905a1ecdfd237cbc36de4e5426e22d9b84866fdadad646a43e7e7c5d429c6"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.i686-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fcea418a09921a6f20f914993a6d936f7e57d51a"
os = "windows"

    [[oneTBB.download]]
    sha256 = "8b2c2d210f8cec2cf6111f1ec678427b0facade17eeebe7fc60abab54aa57807"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.i686-w64-mingw32-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28ff17bf4f5da5a3fe925387dcbd6c8c27ebede1"
os = "windows"

    [[oneTBB.download]]
    sha256 = "5e55500d19ff0d1a660912bc794276ac791154b89b94cbf4d06a6435161de388"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.i686-w64-mingw32-cxx11.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "174fa735d6397dfd8a3c944f97d9540751bef26e"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "a507f03dd41b3db7ff768f187a432ec3defc85739be34a19bbcebfdffba7c5aa"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "067262e048fdeff2bc577ad8ca476f9b55f98a29"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "7e9f4ea1784e727680de054ec14f440af791ba657555aeeb17f2ea4415ea71dd"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "ee2243fa6549c3cc31bef61e80551e96f3c50dac"
os = "macos"

    [[oneTBB.download]]
    sha256 = "36efab2aa4dfc7817f0198a2a25e485d559dd5291089a4f3b28dbce25f6fb6b5"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.x86_64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd52f51495e212fb21df2420a1cc6506f1b567ff"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "2dc25a1344aa645d7273680d46fc8f750b5b5368a1925a4204c0d26b4ca8aa95"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.x86_64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d7eb535e04c99b3ec059c46c0431337c9c452e3"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "e82d2313f68302c137f9c745dba2a5dd7603011c5af81ce3bfed3ce249d28f87"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.x86_64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "baff3c2efe342c61a4cc0b365d21631813fa2668"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "1e111fce9971b1aeef005d12ca29c52417615bba6d3896c69258925abfecad54"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.x86_64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "961607036642a7367a70f5e88e19933022696af1"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "e58d9a34d8d2055a1760eb21ff4220508b38bc7526660dbab8ffcf13a8103627"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.x86_64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "d4c88eeaf35959ce6dffcb0bb2e924c4efc877ca"
os = "freebsd"

    [[oneTBB.download]]
    sha256 = "17b61eae1970801082183fef510748bc5b32aafd0bcfd78ef053c74edf8db0d4"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.x86_64-unknown-freebsd.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "85d6bc1bc74b44df4bf9baa641d43275c7f1b977"
os = "windows"

    [[oneTBB.download]]
    sha256 = "2ec8b8efc01779a269160ad62ed208a35e6f0a8c279767031483accefb72484b"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a80da89d0fb528913efffff81a0cf1e2ab988cb2"
os = "windows"

    [[oneTBB.download]]
    sha256 = "49f4b1bb4c5fce2dcfd1b86516584cc4cca3067031a08b5ed8726862b66426ec"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.12.0+0/oneTBB.v2021.12.0.x86_64-w64-mingw32-cxx11.tar.gz"
