[[oneTBB]]
arch = "aarch64"
git-tree-sha1 = "d2433e51d78fbea1427a6c9b0beb177c18c9eb21"
os = "macos"

    [[oneTBB.download]]
    sha256 = "59f2c0e4f6267d3b4cbd3e9c843dc8e3411eb19a16bfba295df8d392450cfd0f"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.aarch64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c62237cd4ad3d70ea66c80eaa417b1de35c9cb21"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "92ba778ffeda7dd3ac3fa00d0fab8bf7e001c5ddc098345ab742a49e1904a8c0"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.aarch64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26274336938aad53e1d842a567f0e0dfb8f80ddc"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "46aeb4b9b7b40eade0b08ccbf7ebaa6f81acc8ad293923f3289e4e7835dc6d8a"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d65690a1aa18f975a8077229eaeb8c37fa1334c9"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "ac2d675de527172ac2256d5a28e8d640d9a579a9e4f2423fff2d8391d78df8bf"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.aarch64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3ab943f8893c9a4c8bb73c8fb9a1541f80c30eb"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "9dba72af026796347dcaf9b6c3003611d35280bd5789bd5b2d6a690fbed33b8e"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c40414dd6caf7bec3b43995df8c32f93f6aa29d"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "0b91e20bc3bc47c0ccec98cbb3fbce138af86f50809ea2a64f1e0a4e19bccd5e"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.i686-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13e593e9dfce28e8d353a1f5b94eba055219f16d"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "35615548703b3d974bb4016e1b2e381029f4760064a974a5c872a8b586399bd5"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.i686-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0ab6b6d19f2945bd70b6bd0f42cd8319cdd1563"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "c09f05d57488d0b79241d954f1e719e5e84c39572dfe7b3890864c7d99de19ff"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.i686-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efa3dab6b167dd639eca14a697842efa6afe6cd4"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "aade0dfc2483fb09dd023ba5da4f3cb13fd25432c4ba5d52a8b7e9bef012596f"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.i686-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "436520915944c156009bf045a1a978a0b1bed81f"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "9c1658b590281abd4b5ca4b73714975b4ec3aef8e2f3781096f057db845845bb"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b9e654fee2d60fffa9c8ce946af6444064bc744"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "163d5c759b8e8e7bc2dd5def93092f9fb3eeeb36ab278000c65253a82e15248a"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "2757cb95e532c37e172fcedc2381cf318c5480e7"
os = "macos"

    [[oneTBB.download]]
    sha256 = "a46c5e47defc899ffd440c6abda826ce3f1ced1055c8b171ce212eb30c205304"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.x86_64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "71b7173bc3a51a85e34623938dc540ff5cf422ff"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "a5c88ab98b8e5b845f5e667bd92c2ad89713084d392dec08442d7888cf345d88"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.x86_64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffdc380ec1dbf68850a0ef72732236cf8cfc90ed"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "0cfcb671fb9f9d62a44ea0c37637071dc8c85d095372cca711ed8b98798c5953"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0dca64ee0c6c58c04de5d49d7f353945b9fca459"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "2d863c8b386902d29f9443720eb70c9213c8273af60132891460b8d6bc0cb57d"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.x86_64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b60fd3bf0963eba4e4ed6504665980228b2ee11"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "156e433f28601bce5d46a721c2f1ce785fe7d62e32220310732c7ae504345023"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "7554242ab3fd0f6535c24236c48af3bef9810549"
os = "freebsd"

    [[oneTBB.download]]
    sha256 = "f778c998ab6eb4fcdfe92ce6284582af097b56fcf1930fc6d44425e24f2b7a39"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.2.1+1/oneTBB.v2021.2.1.x86_64-unknown-freebsd.tar.gz"
