[[oneTBB]]
arch = "aarch64"
git-tree-sha1 = "6ef301e12dff07a151325e3e8cd5785b61d324fe"
os = "macos"

    [[oneTBB.download]]
    sha256 = "d35e853b6aba1bb5c79b6ab029dbd8829e344d73fa999ee23f8e560362f723b0"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.aarch64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dee064046a47c18f335f3f9388003e3f0b44af87"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "90661b0a6561f2b447a5bdd1828f2064a1c487bf2aff98454a659a8deac990a3"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.aarch64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6483ac61d7f96c9f0563a4a7739190b299dab336"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "741db2a516ba46ec4c89ff271138dec256b5eaff06412be01e8782c571e8afed"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.aarch64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db8e4902a79eea06f9ba1ab80d07ecbba9fe630e"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "68a07f53e19ce730c4105294db1f0b240d84d015b2594c3127157ce0e7d3b54a"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.aarch64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aacdd56d73bb7ee41dadc4cb998b2b4042581aeb"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "fcbda504ec99455a6f0e458358934066aec7cdf646e547429a2af6c7b0a076a3"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.aarch64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6e2e06bd827102237e5f9b5795e2624233e1950"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "46404ffe16ca388aa114b78b1a81f4c2f3d499d91fa92829cb446d189106dd03"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.i686-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3830727353ff397b79285f24723bec3a0d8877d6"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "c102fc0fc53fb0eabae91becd2fb5b837edfd16b2b14208e8f54b3d9444c9344"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.i686-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39fe6b34e03125d986a2655bf00aa34ffe054390"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "ce994cd607f8bd64998825197f032988d06d1e0c3b516ad0e961dc3138198737"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.i686-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee26d93b249d47058bd2e807e4968917a60cc954"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "b610b1cfcc1b53cdfcb73ba1bc584e8312d5112adefe3df507a40adbfc071c42"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.i686-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2cda02d6ef9cfad50456f1fa65b6bc3887276716"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "d5cd32fd8d50550954ac1d8d084a9294741208a52ffd08f64a34b1961f390edd"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d378f5da115d4d3ec1dba4fb8e03e2a49bdb3271"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "1d1c003717b115b436dca946afb22ddd4508a8e8ab1dc58c67c480fd21e02e01"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "461345744210e9945487f63615ab0e4863f96561"
os = "macos"

    [[oneTBB.download]]
    sha256 = "f30913fedf7ec54456fb3fba29df70fa6de2c07233431193bcfc0966ff785e4a"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07e876f4beede7e964f45dc23eea4be2b121db6d"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "20a89a4da4189246f6fe9de54817cc1a69c73994d03ff0722a8a36802c005eeb"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cbbb27d567a5cfa456da6fdad3974eed39996b3"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "109ea0476edbe84fcd8713921ab5b66689a3c4fb84e7e4c4c85cc1b298bfa339"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3059c7acd10fe4827dd3cfe4d7f09600ca0b10d6"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "93228c8b2eeb77fda4b6cf87142302626a95e88a99a08708b1bf6c46ceb00e9f"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8250c8a358a250f7e55715f4a00ea8fc683adc1b"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "26fe1a7ca0752bf9ff8f12beacf06596c4657be366cad90497d446275b31111e"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "d2d2422f2d324dd6d5dcf22f54deafc4f91e6911"
os = "freebsd"

    [[oneTBB.download]]
    sha256 = "94374625b0479ade30c7931be678f9e7c05ab42815a9940efa3f4c8996d82a5b"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-unknown-freebsd.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ef45b6d1eb5c0984457e779cdfb3089615fe3436"
os = "windows"

    [[oneTBB.download]]
    sha256 = "fd552723a791bdb68bca9444b984e704177c86eb3ff07bf37023ea39415e73f1"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd188b58ab2a60a75b0d65e2c5fbb2123aa0d81c"
os = "windows"

    [[oneTBB.download]]
    sha256 = "c7d18d5a21d232457bb4aad231e2a6458072a4ae8dfbae37915623433a0d7a06"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-w64-mingw32-cxx11.tar.gz"
