[[oneTBB]]
arch = "aarch64"
git-tree-sha1 = "c8eaa85d1136d1ce6df797b1adc3a2c13a94944b"
os = "macos"

    [[oneTBB.download]]
    sha256 = "cbd1a1b6ab6c26f6126de06edbb6e2843583e1095792a0297d217b92ac659f0e"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.aarch64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68724cf89bb5230de20590dfb3d6b09d0de707a5"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "47d257fffc9f659ef0c8b0c659987dce3b722d0fa1c90f26532901cb02d711e5"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.aarch64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "450648692f7e31036e554881e77badeb52bdbb7e"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "d8bc258f5bddce7f9d26f1b167c05a06e6061799f55b0d1119e94dc32c4a1c70"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.aarch64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "efb30dda911a9908c49ac4136a6c0006c4e62920"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "b8944f5c5583f76523d94a8374283f50e3034cc37d00d40e36910cb1aa3aee55"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.aarch64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80caec44761d8b07b6457bf78291a3523e0bb879"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "ad43b61d32150d6aa76fe35f626465c8051bd8cf59a7a547e3a970c05caa39f8"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.aarch64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88f8b911252d3ab9b86606feeaf8f50263cb9d04"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "2d1a9817dcfc11a625041a2526a690efa1d38858cfe8b628052674b5d85da649"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eaf0e827dcf1f4a36bb213a2987246776a48338c"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "ff74f5355ccd6c1c6a366fb8cbeb951df6853f995604dc44c4ab310d881e42d5"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "696c7164ef3390a960d40e583b7090cc769c6add"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "fe61dd057890ae5384abd2342fd5461226f192a930e1c4945eaeb323a86d465e"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddd5c3670a1bdf5b3ebfa38fbfa2192975e1f803"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "f4f05527339c649cc8f46d8d7bb618dc1173ae577e729b5cebc86c9fff89e205"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b2951e3d1acf26cefd99d8ddc4f9a4fca438231"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "ad1e4cee4e2c56734bf53f9d7c54ea3435cac48d18fb3da349ee54f6f4633ab9"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "780f1304efd5d023e67ffb2f5bc30974a6023c07"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "bee81edd01133f53f9ee1faf36e5779f4734b3e7ea981041a72402e22133ffae"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "782e0996ffd70fc6186184c5bd9339e78c40be79"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "ce8f4db390c04b97b149e37f014da928b5325de215328fee09c22145c0b0269d"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e83ebe293b24382469221af956bbd4e7ddd4f4b"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "5b2f0feaae2ff4e1f2627929d4aacb87ca72cbcf8ea642c7f0774ce0cc50730b"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c06362566cf9f71eea27a323e680ce5040b31692"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "3527ee9458920e7745d78c33546cdfdf23f27e04afb720e7988a8617a0af82d2"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.i686-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28cf2bf07d98bf971a40a2cf12ea722cdb224dbf"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "81580413b7d2ac2d6ce29ed308ffb339569909021f8e28f492ef3b4e79c15c12"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.i686-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54faf0f3b0671229e6e610f5ec0bb72fd023d146"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "ddd1defb61b558f1613f39a4c33bcf93824a966475db8fc347f3891f312ac241"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.i686-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9c7aad29cf81904c97d6881970bf47a9e896213"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "677e39344bb250475be17d35bdbe6d3a317356c74ffb6766ae99e0f14de8287a"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.i686-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5e6bea64c9d0933d2ab2835d71aab8902e0021b"
os = "windows"

    [[oneTBB.download]]
    sha256 = "1c58a227f35a83519fcaaa1b5ff92e99ac214dcddcca970e9769b87f2bd8a476"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.i686-w64-mingw32-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ffebf3b8b934877408621ac28d31cded9b4a279"
os = "windows"

    [[oneTBB.download]]
    sha256 = "2e75d1b51374a4ccc6b7006ed0dfb1a73ce6363b72aaad243aeee05ef08b440c"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.i686-w64-mingw32-cxx11.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ea04239d5e4277719319505e2f0113b9dc30ee1b"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "f44434e6db1d6144fd13792f41bc7d211169e332d6434a156015712e81a411d4"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72a747a61b95a0dbba3a9f1c6760c18de5810a2e"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "316d4782b6d903418f9544035bc4cc403cecc68f7ac85437ecb64cc9eeb11c11"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "a418b3f99f134898495d5f9111056fce0b61da36"
os = "macos"

    [[oneTBB.download]]
    sha256 = "29736cec25b8ea0be34c9a2d761def3e09288418b30d7cbd27e28e1b598c4629"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.x86_64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ffdedb330c8bdb22ce9472e442992009adc6d59"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "e7fe4f9bac1b5945b7acdb101f9188af7ef9cc2e3da935d068dc0f4060e4645f"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.x86_64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a29610de631b31474d7dd1ba09e062479119158f"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "be885813f5f04cbe5f2439d195cc2b921254d32f4d7ee4d4ae661f390dd6fabd"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.x86_64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1d83efd12904dfd53e12f1b7400b0a9729d1bac"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "eec6ab2369807a926db0d87d1b0a8f3696da092f90825edad60b2aec5ff6248f"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.x86_64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ca58e8bc5b981586fcaa9e920adf5833549c506"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "79ff0cec3cc54b506cf63416865231bbfa5eccc0a140414780e394efe8f45c81"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.x86_64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "98a9248a062a5fd817f20bbfa076b979c24356da"
os = "freebsd"

    [[oneTBB.download]]
    sha256 = "8a1968cce35434ee640dbfb534bf867aea290d9c85665c7b6210abd0a5bcb22a"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.x86_64-unknown-freebsd.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9080691bdc9fef310c4660b5a3b1b8954ca3a947"
os = "windows"

    [[oneTBB.download]]
    sha256 = "f9b75f37d7e95f4e24ef7a791eb8ebb1b9896820fb001c40cdcc0c99de474010"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07fbcdd65603ab64f9247feedc32fec7df5201bd"
os = "windows"

    [[oneTBB.download]]
    sha256 = "9c151774c3c4ac4eed73a70d8dbbc05ee71593dcde02589d0b27d76ef9bdf95d"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.9.0+0/oneTBB.v2021.9.0.x86_64-w64-mingw32-cxx11.tar.gz"
