[[oneTBB]]
arch = "aarch64"
git-tree-sha1 = "9dbe26d1dd50db6263efccab6edc373132699d16"
os = "macos"

    [[oneTBB.download]]
    sha256 = "e168473d3966b3ebe939a3d9bdbc02322cdcf0b06098123ff493912129324ed8"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.aarch64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c477412b2ac66f8a970db64eb4597a21b8695fe"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "733604fb0d165b8f7d3fc9ef5391c0e2b1b5ac0da5b9fed03189c6244091843d"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.aarch64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "309939a9429a814c654e615d7a3a78e5cdc2a7ef"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "8924e62a80eef27dbb8edc879c6a4406ba99a0648a3f419c99139b0cf109d33e"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.aarch64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f864c636d83a34b4fcea11d1cf0f17e649fc1677"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "d03cc0a61d04b6d7ab5d58b24fbb84a1e24975e1eb8eecc1dff2be3ce268b00c"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.aarch64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f48e3e341bb920c81915b3502c9ad625db08d83"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "3d88abb5f127b1000b6e074ec2931067a5afc7b66ae243abf8b1f76c422c3c87"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.aarch64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "757c1ec8633a236d8139cf21565b28d7e5872505"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "31103bee29df490ea2ab90ef3e763cabf461225a4ac91b2b33b7d82c16f949c0"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.i686-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89a512420e1d9704f24be56858853f1e9dd66643"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "c812ae7478792086a3110df74d25c3021af5b96b852149da184adedcfa6e82a6"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.i686-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d7f8f15ea0a135b4fe8e164669337885269ea5e"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "f2ce50f19974803a37847c447819f627011c0325946213e3de07d4474bc82dea"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.i686-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f4721909bb60dfbac64027385d0e63a8e35c392"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "c55b27176d80fc274c3aeb58caea929a49257fcd863901f5956d60d13f8fd6f2"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.i686-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afd6d898517ce5ad99a8865b21486c20865b0cbc"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "5013484125a830d98b3a35e6183f17ed73a7e7730cea1ac8f165396f4158f08c"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acf55ab4134d205bb49bb19cafa0c821a0c2c2a8"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "ea7eabf4dbb99377395b87c1a4a26b55ded6799300613aa745c430f8c2f272b7"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "e5930dba9bff3b7c72a100e7335ecebf186fae3b"
os = "macos"

    [[oneTBB.download]]
    sha256 = "cf4aa96f27d920dc586ece175c0b33ded0030f3e824d01210131ac54ab6ac4a2"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.x86_64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a674f66b6e8f63dc0c8dd7b9d4cce6e30edb396f"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "04274969e108b6a0d53f134ceeb2b37618bc128bf3fbd8aadf04e5bcf6e5f0cc"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f48e9e59a258d311c17052e43c6758f01f5799b"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "18bf256fc58fffd3fe515d57a629b9cf5ce32e402fd9069bb21036046f9cf733"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.x86_64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5675164262b311f2be9828c6c830f0496c5331b"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "04a8fae04442934f65a159445cd08468bb3c9b745d80e3212e83c55d9fcf104c"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.x86_64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f45c2cf825632f388026a7e43fe42857ee275dd"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "fd76ab97ca0d94726be7799231bad2f3589c6f790c606acff7baa5628ff230d0"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.x86_64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "307454591b7d6872b75fdbbec9513aeb9af6f9a0"
os = "freebsd"

    [[oneTBB.download]]
    sha256 = "4520235774ab8e8fa81eb8349327c6435acf58a4409dceff1d2edd2410c1ecfa"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.4.1+0/oneTBB.v2021.4.1.x86_64-unknown-freebsd.tar.gz"
