[[oneTBB]]
arch = "aarch64"
git-tree-sha1 = "d5ed2a4dd91126141baab38431695aaac01f573c"
os = "macos"

    [[oneTBB.download]]
    sha256 = "bacc0f8ce8f246d79f01e321d6beff6409ab9636933ad1706fa1d9dace75f47c"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.aarch64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6dbe2f302f0d797e94cab0a489d022a53e44c6b0"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "69150ae6ea45601c80be18aa391dc6068ff525f1e37c303ad678f041e52abd5a"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.aarch64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2467122020a5f476ca1c2ecc415660196861558"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "55a61d402d27681235a62d258f281c716c3e139ce7ad5aaf66e3901ae8793c77"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.aarch64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f793cf05817ea1e0dec9e8c8d4f2ad07744b5aea"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "f0ea98e650a4dbcf92ae31aaeead5be4d8e882ad0f2a97de91922b22bcdcc550"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.aarch64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de964010b1fff62e81377cf71fe496aad0ce1322"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "bc91a33a1505e8ada48fd592c54058c17df8308c9fff77b9ad0458d08d529559"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.aarch64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86dcfe7700739ea704ef1080921e554d3e4fce50"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "5faef315161ac5e0c6793d8687129c9afc9583e27b3a8daadf39ce2c84102e47"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea360df464d9c94ce50e88611ee33e287fec86fa"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "9e77db8608e7ab8b9fd55b06f2bf6e13e3c4442f3a2e83c6ad14b7529457c57b"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "e1eff2563310650510b2869b81682b482f79cc1e"
os = "macos"

    [[oneTBB.download]]
    sha256 = "e89f96287ca26f0421010a9c1ea780988b0af1264dde2f2adfdb416d7ddd0aa8"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "867ab97c60b004c0739eaa20ef959969984111f2"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "c53883ed9e6d06e271d6551eb1abf2caa54957d58ca8621d88c0a5744450e60f"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f81490a50222d5107ded627fb5ea62492a49aa7f"
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "3f404c1bf132fa9a8e3c36e364ae011dd7b3c1a97ca3633902baf5efbf0ab7c2"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6e6d59fa3b4bef422ea3366c1b2b0fff6ab4f9d2"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "3495a59111c327891bad543212d0d2a9e195f076082d32722b533e71c0bd0e02"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a17c4f4368bc7a2fd1f53e98aee5882322860bf"
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "9836fed931b60e87938e5250bd576f3153d47548bc17ea0f2ad036f3fb4252c4"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "4d6b710f7ee51f4158f1dbbe578a0aa9fc89ca3e"
os = "freebsd"

    [[oneTBB.download]]
    sha256 = "5b6c00ecff88cc9726cd07ae94f71c29cce99c26187a5b67bae39a809e092b6f"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2021.5.0+0/oneTBB.v2021.5.0.x86_64-unknown-freebsd.tar.gz"
